# User config
author: "vivian fairy say hello "
tagline: "Pineapple Certfied Jekyll Theme"
description: "the apple the banana and Pineapple are my best"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: 785622997@qq.com
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: ajdbvivian

# Site config
baseurl: ""
url: "https://ajdbvivian.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed